### ISSUE TITLE
Let it breathe. Add more negative space, use better title font/color

### ISSUE THREAD

**Issue by karan** [karan/karan.github.io#36]

**Comment by karan** [comment]
```css
.intro {
  font-size: 3em;
  border-bottom: 5px solid #444;
  margin-bottom: 1em;
}


h1, h2, h3 {
  line-height: 2;
  margin: 0;
}


p {
  margin: 0 0 2em;
  line-height: 1.8em;
}


body {
  margin: 20px auto;
  max-width: 640px;
  line-height: 1.5;
  font-size: 20px;
  color: #444;
  padding: 0 20px;
  font-family: Hind,sans-serif;
}


li {
  line-height: 2em;
}
```
